=== Beira-BF/t4ss-event/original-data/GENIAtypes/GENIA_event_20.dtd
<!-- ============================================================ -->
<!-- DTD for Genia corpus with term&event annotation              -->
<!-- written by Jin-Dong KIM <jdkim@tsujii.is.s.u-tokyo.ac.jp>    -->
<!-- Date of last modification: November 11 2005                  -->
<!-- ============================================================ -->

<!-- ============================================================ -->
<!-- Labels for term&event annotation                             -->
<!-- ============================================================ -->
<!ENTITY % term.class "(
Element | Inorganic_compound | Organic_compound_other |
Amino_acid_monomer | Peptide | Carbohydrate | Lipid | protein |
Protein_complex | Protein_domain_or_region | Protein_family_or_group |
Protein_molecule | Protein_substructure | DNA |
DNA_domain_or_region | DNA_family_or_group | DNA_molecule | DNA_substructure | RNA |
RNA_domain_or_region | RNA_family_or_group | RNA_molecule | RNA_substructure |
Nucleotide | Polynucleotide |
Cell_component | Cell_cultured | Cell_natural |
Body_region | Tissue_cultured | Tissue_natural |
Multicellular_organism_natural | Multicellular_organism_genetically_modified |
Unicellular_organism | Virus | Bacterium |
Other | Biological_process | Diagnosis | Disease |
Experimental_method | Molecular_function | Therapeutics
)">

<!ENTITY % word.class "(
C | CC | CD | COLON | COMMA | DT | EX | FJJ | FW | IN | JJ | JJR | JJS |
LQT | LRB | LS | MD | NN | NNP | NNPS | NNS | PDT | PERIOD | POS |
PRP | PRPP | RB | RBR | RBS | RP | RQT | RRB | SYM | TO |
VB | VBD | VBG | VBN | VBP | VBZ | WDT | WP | WPP | WRB | FRAG
)">

<!-- ============================================================ -->
<!-- HIERARCHICAL ELEMENTS                                        -->
<!-- ============================================================ -->
<!ELEMENT Annotation (PubmedArticleSet)>
<!ATTLIST Annotation
		annotates CDATA #REQUIRED
		creator   CDATA #IMPLIED
		created   CDATA #IMPLIED
>

<!ELEMENT PubmedArticleSet (PubmedArticle)>
<!ELEMENT PubmedArticle (MedlineCitation)>
<!ELEMENT MedlineCitation (PMID, Article)>
<!ELEMENT Article (ArticleTitle, Abstract)>
<!ELEMENT Abstract (AbstractText)>

<!-- ============================================================ -->
<!-- BLOCK ELEMENTS                                               -->
<!-- ============================================================ -->
<!ELEMENT ArticleTitle (sentence | event | staticrel | relation)+>
<!ELEMENT AbstractText (sentence | event | staticrel | relation)+>
<!ELEMENT PMID (#PCDATA)>

<!-- ============================================================ -->
<!-- LINGUISTIC ELEMENTS                                          -->
<!-- ============================================================ -->
<!ELEMENT sentence	(#PCDATA | cons | term | frag | gene-or-gene-product)*>
<!ATTLIST sentence	id ID	#REQUIRED>

<!ELEMENT cons		(#PCDATA | cons | term | frag | gene-or-gene-product)*>
<!ATTLIST cons 
		sem CDATA #REQUIRED
		lex CDATA #REQUIRED
		id  ID    #REQUIRED
>

<!ELEMENT term		(#PCDATA | term | frag | gene-or-gene-product)*>
<!ATTLIST term
		sem %term.class;	#IMPLIED
		lex CDATA	#IMPLIED
		id  ID		#REQUIRED
		manual-T2G-term-processing (True | False) #IMPLIED
		manual-A-term-processing (True | False) #IMPLIED
		T2G-Is-restructure (True | manual | done) #IMPLIED
		frags CDATA #IMPLIED
		full-lex CDATA #IMPLIED
		old-frag-id CDATA #IMPLIED
		orig-frag-lex CDATA #IMPLIED
		remap-to	CDATA #IMPLIED
		site	CDATA #IMPLIED
		appos		(YES|NO)	"NO"
		idref	CDATA	#IMPLIED
>

<!ELEMENT frag		(#PCDATA | term | gene-or-gene-product)*>
<!ATTLIST frag
		id  ID		#REQUIRED
		idref IDREF	#IMPLIED
		remap-to CDATA	#IMPLIED
		site	CDATA #IMPLIED
>

<!ELEMENT gene-or-gene-product	(#PCDATA | frag)*>
<!ATTLIST gene-or-gene-product
		id  ID		#REQUIRED
		equiv		IDREF	#IMPLIED
		appos		(YES|NO)	"NO"
		orig-frag-lex CDATA #IMPLIED
		remapped-to-from	CDATA	#IMPLIED
>

<!-- ============================================================ -->
<!-- ELEMENTS FOR EVENT ANNOTATION                                -->
<!-- ============================================================ -->
<!ELEMENT event (type, (theme | site | locTo | locFrom | product | cause | csite)*, clue?, comment?)>
<!-- ELEMENT event (type, theme*, site*, product*, cause*, csite*, clue, comment?) -->

<!ATTLIST event
		id		ID							#REQUIRED
		assertion		(exist|non-exist)			"exist"
		uncertainty 	(certain|probable|doubtful) "certain"
		copy-of CDATA #IMPLIED
>

<!ELEMENT type EMPTY>
<!ATTLIST type class		CDATA	"UNCLASSIFIED">
<!ATTLIST type subclass		(migration|presence|ToLook)	"migration">
<!ATTLIST type
		idref		IDREF	#IMPLIED
>

<!ELEMENT theme EMPTY>
<!ATTLIST theme
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		manual-multi-idref-processing (True | Done) #IMPLIED
		judged-out	CDATA	#IMPLIED
>

<!ELEMENT site EMPTY>
<!ATTLIST site
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		site_of		CDATA	#IMPLIED
>

<!ELEMENT locTo EMPTY>
<!ATTLIST locTo
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
>
<!ELEMENT locFrom EMPTY>
<!ATTLIST locFrom
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
>
<!ELEMENT csite EMPTY>
<!ATTLIST csite
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
>

<!ELEMENT product EMPTY>
<!ATTLIST product
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
>

<!ELEMENT cause EMPTY>
<!ATTLIST cause
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		manual-multi-idref-processing (True | Done) #IMPLIED
		judged-out	CDATA	#IMPLIED
>

<!ELEMENT clue  (#PCDATA | clueType | linkTheme | linkCause | clueTime | clueLoc | atLoc | fromLoc | toLoc | envLoc | corefTheme | corefSite | corefProduct | corefCause | corefLoc | clueExperiment | clueSpec)*>

<!ELEMENT clueType		(#PCDATA | atLoc)*>
<!ELEMENT linkTheme		(#PCDATA)>
<!ELEMENT linkCause		(#PCDATA)>
<!ELEMENT clueTime		(#PCDATA)>
<!ELEMENT clueLoc		(#PCDATA)>
<!ELEMENT atLoc			(#PCDATA)>
<!ELEMENT fromLoc		(#PCDATA)>
<!ELEMENT toLoc			(#PCDATA)>
<!ATTLIST toLoc
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>
<!ELEMENT envLoc		(#PCDATA)>
<!ELEMENT clueExperiment	(#PCDATA)>
<!ELEMENT clueSpec		(#PCDATA)>

<!ELEMENT corefTheme		(#PCDATA)>
<!ATTLIST corefTheme
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT corefCause		(#PCDATA)>
<!ATTLIST corefCause
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT corefSite		(#PCDATA)>
<!ATTLIST corefSite
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT corefProduct		(#PCDATA)>
<!ATTLIST corefProduct
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT corefLoc		(#PCDATA)>
<!ATTLIST corefLoc
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT comment		(#PCDATA)>

<!-- ============================================================ -->
<!-- ELEMENTS FOR STATIC RELATION ANNOTATION                                -->
<!-- ============================================================ -->
<!ELEMENT staticrel (SRtype?, GGP, BioTerm, tags?, note?)>
<!--ELEMENT staticrel (SRtype, GGP, BioTerm, SRcomment?)-->
<!ATTLIST staticrel
		id		ID	#REQUIRED
		relation	(Yes | No | Unsure) "Yes"
>

<!ELEMENT relation (SRtype, GGP, BioTerm, tags?, note?)>
<!ATTLIST relation
		id		ID	#REQUIRED
		relation	(Yes | No | Unsure) "Yes"
>

<!-- -->
<!ELEMENT SRtype EMPTY>
<!--<!ATTLIST SRtype class		(Equivalent | Specification | Modified_Protein | Isoform | Mutant | Recombinant | Precursor | Experimental_material | Amino_Acid_Motif | Amino_Acid | Peptide| Gene_Component | Protein_Complex | GGP_Group | Chromosomal_Locus | Other)	"Protein_Complex">-->
<!ATTLIST SRtype class		(Equivalent | Specification | Modified_Protein | Isoform | Mutant | Recombinant | Precursor | Experimental_material | Amino_Acid_Motif | Amino_Acid | Peptide| Gene_Component | Protein_Complex | GGP_Group | Chromosomal_Locus | Participate | Other)	"Participate">

<!ELEMENT GGP EMPTY>
<!ATTLIST GGP
		idref		IDREF	#REQUIRED
>

<!ELEMENT BioTerm EMPTY>
<!ATTLIST BioTerm
		idref		IDREF	#REQUIRED
>

<!ELEMENT tags		(#PCDATA)>

<!ELEMENT note		(#PCDATA)>

=== Beira-BF/t4ss-event/original-data/GGP-XML_event-and-relation/file_1.xml
<?xml version='1.0'?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION EVENT 2.0//EN" "../GENIAtypes/GENIA_event_20.dtd">
<Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=000000000" created="26/03/2010" creator="Tomoko Ohta"><PubmedArticleSet><PubmedArticle><MedlineCitation>
<PMID>000000000</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">A Bacterial Guanine Nucleotide Exchange Factor Activates ARF on <term id="T1" sem="Bacterium">Legionella</term> Phagosomes</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2">The intracellular pathogen <term id="T2" sem="Bacterium">Legionella pneumophila</term> subverts vesicle traffic in eukaryotic host cells to create a vacuole that supports replication .</sentence>
<sentence id="S3">The dot/icm genes encode a protein secretion apparatus that <term id="T3" sem="Bacterium">L. pneumophila</term> require for biogenesis of this vacuole .</sentence>
<sentence id="S4">Here we show that <term id="T4" sem="Bacterium">L. pneumophila</term> produce a protein called <gene-or-gene-product id="G3">RalF</gene-or-gene-product> that functions as an exchange factor for the ADP ribosylation factor ( ARF ) family of guanosine triphosphatases ( GTPases ) .</sentence>
<sentence id="S5">The <gene-or-gene-product id="G8">RalF</gene-or-gene-product> protein is required for the <term id="T6" sem="Biological_process">localization</term> of ARF on phagosomes containing <term id="T5" sem="Bacterium">L. pneumophila</term> .</sentence>
<event id="E1"><type class="Localization" idref="T6"/><theme idref="G8"/></event>
<sentence id="S6"><term id="T7" sem="Biological_process">Translocation</term> of <gene-or-gene-product id="G10">RalF</gene-or-gene-product> protein through the phagosomal membrane is a dot/ icm-dependent process .</sentence>
<event id="E2"><type class="Localization" idref="T7"/><theme idref="G10"/></event>
<sentence id="S7">Thus , <gene-or-gene-product id="G11">RalF</gene-or-gene-product> is a substrate of the Dot/Icm secretion apparatus .</sentence>
</AbstractText>
</Abstract></Article></MedlineCitation></PubmedArticle></PubmedArticleSet></Annotation>

=== Beira-BF/t4ss-event/original-data/T4SS-virulence-relation/file_27.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION EVENT 2.0//EN" "../GENIAtypes/GENIA_event_20.dtd">
<Annotation created="26/03/2010" creator="Tomoko Ohta" annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=000000000">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>000000000</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">Selfish DNA in Protein-Coding Genes of Rickettsia</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2">Rickettsia conorii , the aetiological agent of Mediterranean spotted fever , is an intracellular bacterium transmitted by ticks .</sentence>
<sentence id="S3">Preliminary analyses of the nearly complete genome sequence of R. conorii have revealed 44 occurrences of a previously undescribed palindromic repeat ( 150 base pairs long ) throughout the <term id="T1" sem="Cell_component">genome</term> .</sentence>
<sentence id="S4">Unexpectedly , this repeat was found inserted in-frame within 19 different R. conorii open reading frames likely to encode functional proteins .</sentence>
<sentence id="S5">We found the same repeat in proteins of other Rickettsia species .</sentence>
<sentence id="S6">The finding of a mobile element inserted in many unrelated genes suggests the potential role of selfish DNA in the creation of new protein sequences .</sentence>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>

=== Beira-BF/t4ss-event/original-data/T4SS-virulence-relation/file_9.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION EVENT 2.0//EN" "../GENIAtypes/GENIA_event_20.dtd">
<Annotation created="26/03/2010" creator="Tomoko Ohta" annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=000000000">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>000000000</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">Bacterial <term id="T6" sem="Biological_process">type IV secretion</term> : <term id="T11" sem="Cell_component"><term id="T7" sem="Biological_process">conjugation</term> systems</term> adapted to deliver effector molecules to host cells</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2">Several bacterial pathogens utilize <term id="T12" sem="Cell_component">conjugation machines</term> to <term id="T8" sem="Biological_process">export</term> effector molecules during infection .</sentence>
<sentence id="S3">Such systems are members of the type IV or &apos;adapted <term id="T9" sem="Biological_process">conjugation&apos;</term> secretion family .</sentence>
<sentence id="S4">The prototypical <term id="T13" sem="Cell_component">type IV system</term> is the <term id="T1" sem="Bacterium">Agrobacterium tumefaciens</term> <term id="T14" sem="Cell_component">T-DNA transfer machine</term> , which delivers oncogenic nucleoprotein particles to plant cells .</sentence>
<sentence id="S5">Other pathogens , including <term id="T2" sem="Bacterium">Bordetella pertussis</term> , <term id="T3" sem="Bacterium">Legionella pneumophila</term> , <term id="T4" sem="Bacterium">Brucella spp</term> . and <term id="T5" sem="Bacterium">Helicobacter pylori</term> , use <term id="T15" sem="Cell_component">type IV machines</term> to <term id="T10" sem="Biological_process">export effector</term> proteins to the <term id="T16" sem="Cell_component">extracellular milieu</term> or the mammalian cell <term id="T17" sem="Cell_component">cytosol</term> .</sentence>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>

=== Beira-BF/t4ss-event/original-data/GGP-XML_event-and-relation/file_16.xml
<?xml version='1.0'?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION EVENT 2.0//EN" "../GENIAtypes/GENIA_event_20.dtd">
<Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=000000000" created="26/03/2010" creator="Tomoko Ohta"><PubmedArticleSet><PubmedArticle><MedlineCitation>
<PMID>000000000</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">Interactions of <gene-or-gene-product id="G1">VirB9</gene-or-gene-product> , <gene-or-gene-product id="G2">-10</gene-or-gene-product> , and <gene-or-gene-product id="G3">-11</gene-or-gene-product> with the Membrane Fraction of Agrobacterium tumefaciens : Solubility Studies Provide Evidence for Tight Associations</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2">The eleven predicted gene products of the Agrobacterium tumefaciens virB operon are believed to form a <term id="T7" sem="Cell_component">transmembrane pore complex</term> through which <term id="T1" sem="Biological_process"><term id="N1" sem="Cell_component">T-DNA</term> export</term> occurs .</sentence>
<event id="E1">
<type class="Localization" idref="T1"/>
<theme idref="N1"/></event>
<sentence id="S3">The <gene-or-gene-product id="G5">VirB10</gene-or-gene-product> protein is required for <term id="T2" sem="Biological_process">virulence</term> and is a <term id="T8" sem="Cell_component">component</term> of an aggregate associated with the <term id="T9" sem="Cell_component">membrane</term> fraction of A. tumefaciens .</sentence>
<event id="E6">
<type class="Positive_regulation"/>
<theme idref="T2"/>
<cause idref="G5"/>
<clue>The VirB10 protein <clueType>is required</clueType> <linkTheme>for</linkTheme> virulence and is a component of an aggregate associated with the membrane fraction of A. tumefaciens .</clue>
</event>
<sentence id="S4">Removal of the putative membrane-spanning domain ( amino acids 22 through 55 ) disrupts the membrane topology of <gene-or-gene-product id="G6">VirB10</gene-or-gene-product> ( J . E . Ward , E . M . Dale , E . W . Nester , and A . N . Binns , J . Bacteriol. 172 : 5200-5210 , 1990 ) .</sentence>
<sentence id="S5">Deletion of the sequences encoding amino acids 22 to 55 abolishes the ability of plasmid-borne <gene-or-gene-product id="G7">virB10</gene-or-gene-product> to complement a null mutation in the <gene-or-gene-product id="G8">virB10</gene-or-gene-product> gene , suggesting that the proper topology of <gene-or-gene-product id="G9">VirB10</gene-or-gene-product> in the <term id="T10" sem="Cell_component">membrane</term> may indeed play a crucial role in <term id="T3" sem="Biological_process"><term id="T16" sem="Cell_component">T-DNA</term> transfer</term> to the <term id="N3" sem="Cell_natural">plant cell</term> .</sentence>
<event id="E2">
<type class="Localization" idref="T3"/>
<theme idref="T16"/>
<locTo idref="N3"/></event>
<event id="E5">
<type class="Regulation"/>
<theme idref="E2"/>
<cause idref="G9"/></event>
<sentence id="S6">Western blot ( immunoblot ) analysis indicated that the observed loss of <term id="T4" sem="Biological_process">virulence</term> could not be attributed to a decrease in the steady-state levels of the mutant <gene-or-gene-product id="G10">VirB10</gene-or-gene-product> protein .</sentence>
<sentence id="S7">Although the deletion of the single transmembrane domain would be expected to perturb <term id="T5" sem="Biological_process"><term id="N2" sem="Cell_component">membrane</term> association</term> , <gene-or-gene-product id="G11">VirB10</gene-or-gene-product> 22-55 was found exclusively in the membrane fraction .</sentence>
<event id="E3">
<type class="Localization" idref="T5"/>
<theme idref="G11"/>
<locTo idref="N2"/></event>
<sentence id="S8">Urea extraction studies suggested that this <term id="T6" sem="Biological_process">membrane localization</term> might be the result of a <term id="T11" sem="Cell_component">peripheral membrane</term> association ; however , the mutant protein was found in both inner and <term id="T12" sem="Cell_component">outer membrane</term> fractions separated by sucrose density gradient centrifugation .</sentence>
<event id="E4">
<type class="Localization" idref="T6"/></event>
<sentence id="S9">Both wild-type <gene-or-gene-product id="G12">VirB10</gene-or-gene-product> and wild-type <gene-or-gene-product id="G13">VirB9</gene-or-gene-product> were only partially removed from the <term id="T13" sem="Cell_component">membranes</term> by extraction with 1 % Triton X-100 , while <gene-or-gene-product id="G14">VirB5</gene-or-gene-product> and <gene-or-gene-product id="G15">VirB8</gene-or-gene-product> were Triton X-100 soluble .</sentence>
<sentence id="S10"><gene-or-gene-product id="G16">VirB11</gene-or-gene-product> was stripped from the <term id="T14" sem="Cell_component">membranes</term> by 6 M urea but not by a more mild salt extraction .</sentence>
<sentence id="S11">The fractionation patterns of <gene-or-gene-product id="G17">VirB9</gene-or-gene-product> , <gene-or-gene-product id="G18">VirB10</gene-or-gene-product> , and <gene-or-gene-product id="G19">VirB11</gene-or-gene-product> were not dependent on each other or on <gene-or-gene-product id="G20">VirB8</gene-or-gene-product> or <gene-or-gene-product id="G21">VirD4</gene-or-gene-product> .</sentence>
<sentence id="S12">The observed tight associations of <gene-or-gene-product id="G22">VirB9</gene-or-gene-product> , <gene-or-gene-product id="G23">VirB10</gene-or-gene-product> , and <gene-or-gene-product id="G24">VirB11</gene-or-gene-product> with the membrane fraction support the notion that these proteins may exist as components of multiprotein pore complexes , perhaps spanning both the inner and <term id="T15" sem="Cell_component">outer membranes</term> of Agrobacterium cells .</sentence>
<sentence id="S13"/></AbstractText>
</Abstract></Article></MedlineCitation></PubmedArticle></PubmedArticleSet></Annotation>

=== Beira-BF/t4ss-event/original-data/GGP-XML_event-and-relation/file_5.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION EVENT 2.0//EN" "../GENIAtypes/GENIA_event_20.dtd">
<Annotation created="26/03/2010" creator="Tomoko Ohta" annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=000000000">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>000000000</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">Agrobacterium <gene-or-gene-product id="G1">VirE2</gene-or-gene-product> gets the <gene-or-gene-product id="G2">VIP1</gene-or-gene-product> treatment in plant nuclear import</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2"><term id="T1" sem="Bacterium">Agrobacterium tumefaciens</term> transforms plant cells by targeting a large single-stranded DNA molecule ( T-strand ) to the plant nucleus .</sentence>
<sentence id="S3">The host cell contribution to <term id="T2" sem="Biological_process">nuclear import</term> and transformation is the focus of several current articles .</sentence>
<sentence id="S4">Recently , plant proteins have been identified that promote <term id="T3" sem="Biological_process">nuclear import</term> of the T-strand .</sentence>
<sentence id="S5">In particular , <gene-or-gene-product id="G3">VIP1</gene-or-gene-product> might couple transformation to the importin-dependent nuclear import pathway and deliver the T-strand to chromatin , thereby promoting integration into the <term id="T4" sem="Cell_component">host genome</term> .</sentence>
<sentence id="S6"></sentence>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>

=== Beira-BF/t4ss-event/original-data/T4SS-virulence-relation/file_3.xml
<?xml version='1.0'?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION EVENT 2.0//EN" "../GENIAtypes/GENIA_event_20.dtd">
<Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=000000000" created="26/03/2010" creator="Tomoko Ohta"><PubmedArticleSet><PubmedArticle><MedlineCitation>
<PMID>000000000</PMID>
<Article>
<ArticleTitle>
<sentence id="S1"><term id="T1" sem="Bacterium">Agrobacterium tumefaciens</term> <gene-or-gene-product id="G1">VirB11</gene-or-gene-product> Protein Requires a Consensus <term id="T17" sem="Molecular_function">Nucleotide-Binding</term> Site for Function in <term id="T8" sem="Biological_process">Virulence</term></sentence>
<relation id="R1">
<SRtype/>
<GGP idref="G1"/>
<BioTerm idref="T8"/></relation>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2"><gene-or-gene-product id="G2">virB11</gene-or-gene-product> , one of the 11 genes of the virB operon , is absolutely required for <term id="T9" sem="Biological_process">transport of T-DNA</term> from <term id="T2" sem="Bacterium">Agrobacterium tumefaciens</term> into plant cells .</sentence>
<sentence id="S3">Previous studies reported that <gene-or-gene-product id="G4">VirB11</gene-or-gene-product> is an ATPase with autophosphorylation activity and <term id="T10" sem="Biological_process">localizes</term> to the inner membrane even though the protein does not contain the consensus N-terminal export sequence .</sentence>
<sentence id="S4">In this report , we show that <gene-or-gene-product id="G6">VirB11</gene-or-gene-product> <term id="T11" sem="Biological_process">localizes</term> to the <term id="T15" sem="Cell_component">inner membrane</term> even in the absence of other tumor-inducing ( Ti ) plasmid-encoded proteins .</sentence>
<sentence id="S5">To facilitate the further characterization of <gene-or-gene-product id="G7">VirB11</gene-or-gene-product> , we purified this protein from the soluble fraction of an <term id="T3" sem="Bacterium">Escherichia coli</term> extract by fusing <gene-or-gene-product id="G8">VirB11</gene-or-gene-product> to the maltose-binding protein .</sentence>
<sentence id="S6">The <term id="T18" sem="Molecular_function">maltose-binding</term> protein <gene-or-gene-product id="G10">VirB11</gene-or-gene-product> fusion was able to complement a <gene-or-gene-product id="G11">virB11</gene-or-gene-product> deletion mutant of <term id="T4" sem="Bacterium">A. tumefaciens</term> for tumor formation and also <term id="T12" sem="Biological_process">localized</term> properly to the <term id="T16" sem="Cell_component">inner membrane</term> of <term id="T5" sem="Bacterium">A. tumefaciens</term> .</sentence>
<sentence id="S7">The 72-kDa protein , purified from <term id="T6" sem="Bacterium">E. coli</term> , exhibited no autophosphorylation , <term id="T19" sem="Molecular_function">ATPase activity</term> , or <term id="T20" sem="Molecular_function">ATP-binding activity</term> .</sentence>
<sentence id="S8">To study the importance of the Walker <term id="T21" sem="Molecular_function">nucleotide-binding</term> site present in <gene-or-gene-product id="G14">VirB11</gene-or-gene-product> , mutations were generated to replace the conserved lysine residue with either alanine or arginine .</sentence>
<sentence id="S9">Expression of the <term id="N2" sem="Protein_molecule"><gene-or-gene-product id="G15">virB11</gene-or-gene-product>K175A</term> mutant gene resulted in an <term id="T22" sem="Biological_process">avirulent</term> phenotype , and expression of the <gene-or-gene-product id="G16">virB11</gene-or-gene-product>K175R mutant gene gave rise to an attenuated <term id="T13" sem="Biological_process">virulence</term> phenotype .</sentence>
<relation id="R2">
<SRtype/>
<GGP idref="G15"/>
<BioTerm idref="T22"/></relation>
<relation id="R3">
<SRtype/>
<GGP idref="G16"/>
<BioTerm idref="T13"/></relation>
<sentence id="S10">Both mutant proteins were present at levels three to four times higher than that of <gene-or-gene-product id="G17">VirB11</gene-or-gene-product> in the wild-type strain .</sentence>
<sentence id="S11">The mutant genes did not exhibit a transdominant phenotype on tumor formation in bacteria that were expressing wild-type <gene-or-gene-product id="G18">virB11</gene-or-gene-product> .</sentence>
<sentence id="S12">The mutant proteins also <term id="T14" sem="Biological_process">localized</term> properly to the <term id="N1" sem="Cell_component">inner membrane</term> of <term id="T7" sem="Bacterium">A. tumefaciens</term> , but the <term id="N3" sem="Protein_molecule"><gene-or-gene-product id="G19">VirB11</gene-or-gene-product>K175R</term> protein appeared to be unstable after lysis of the cells .</sentence>
</AbstractText>
</Abstract></Article></MedlineCitation></PubmedArticle></PubmedArticleSet></Annotation>
