=== Beira-BF/t4ss-event/original-data/GENIAtypes/GENIA_event_20.dtd
<!-- ============================================================ -->
<!-- DTD for Genia corpus with term&event annotation              -->
<!-- written by Jin-Dong KIM <jdkim@tsujii.is.s.u-tokyo.ac.jp>    -->
<!-- Date of last modification: November 11 2005                  -->
<!-- ============================================================ -->

<!-- ============================================================ -->
<!-- Labels for term&event annotation                             -->
<!-- ============================================================ -->
<!ENTITY % term.class "(
Element | Inorganic_compound | Organic_compound_other |
Amino_acid_monomer | Peptide | Carbohydrate | Lipid | protein |
Protein_complex | Protein_domain_or_region | Protein_family_or_group |
Protein_molecule | Protein_substructure | DNA |
DNA_domain_or_region | DNA_family_or_group | DNA_molecule | DNA_substructure | RNA |
RNA_domain_or_region | RNA_family_or_group | RNA_molecule | RNA_substructure |
Nucleotide | Polynucleotide |
Cell_component | Cell_cultured | Cell_natural |
Body_region | Tissue_cultured | Tissue_natural |
Multicellular_organism_natural | Multicellular_organism_genetically_modified |
Unicellular_organism | Virus | Bacterium |
Other | Biological_process | Diagnosis | Disease |
Experimental_method | Molecular_function | Therapeutics
)">

<!ENTITY % word.class "(
C | CC | CD | COLON | COMMA | DT | EX | FJJ | FW | IN | JJ | JJR | JJS |
LQT | LRB | LS | MD | NN | NNP | NNPS | NNS | PDT | PERIOD | POS |
PRP | PRPP | RB | RBR | RBS | RP | RQT | RRB | SYM | TO |
VB | VBD | VBG | VBN | VBP | VBZ | WDT | WP | WPP | WRB | FRAG
)">

<!-- ============================================================ -->
<!-- HIERARCHICAL ELEMENTS                                        -->
<!-- ============================================================ -->
<!ELEMENT Annotation (PubmedArticleSet)>
<!ATTLIST Annotation
		annotates CDATA #REQUIRED
		creator   CDATA #IMPLIED
		created   CDATA #IMPLIED
>

<!ELEMENT PubmedArticleSet (PubmedArticle)>
<!ELEMENT PubmedArticle (MedlineCitation)>
<!ELEMENT MedlineCitation (PMID, Article)>
<!ELEMENT Article (ArticleTitle, Abstract)>
<!ELEMENT Abstract (AbstractText)>

<!-- ============================================================ -->
<!-- BLOCK ELEMENTS                                               -->
<!-- ============================================================ -->
<!ELEMENT ArticleTitle (sentence | event | staticrel | relation)+>
<!ELEMENT AbstractText (sentence | event | staticrel | relation)+>
<!ELEMENT PMID (#PCDATA)>

<!-- ============================================================ -->
<!-- LINGUISTIC ELEMENTS                                          -->
<!-- ============================================================ -->
<!ELEMENT sentence	(#PCDATA | cons | term | frag | gene-or-gene-product)*>
<!ATTLIST sentence	id ID	#REQUIRED>

<!ELEMENT cons		(#PCDATA | cons | term | frag | gene-or-gene-product)*>
<!ATTLIST cons 
		sem CDATA #REQUIRED
		lex CDATA #REQUIRED
		id  ID    #REQUIRED
>

<!ELEMENT term		(#PCDATA | term | frag | gene-or-gene-product)*>
<!ATTLIST term
		sem %term.class;	#IMPLIED
		lex CDATA	#IMPLIED
		id  ID		#REQUIRED
		manual-T2G-term-processing (True | False) #IMPLIED
		manual-A-term-processing (True | False) #IMPLIED
		T2G-Is-restructure (True | manual | done) #IMPLIED
		frags CDATA #IMPLIED
		full-lex CDATA #IMPLIED
		old-frag-id CDATA #IMPLIED
		orig-frag-lex CDATA #IMPLIED
		remap-to	CDATA #IMPLIED
		site	CDATA #IMPLIED
		appos		(YES|NO)	"NO"
		idref	CDATA	#IMPLIED
>

<!ELEMENT frag		(#PCDATA | term | gene-or-gene-product)*>
<!ATTLIST frag
		id  ID		#REQUIRED
		idref IDREF	#IMPLIED
		remap-to CDATA	#IMPLIED
		site	CDATA #IMPLIED
>

<!ELEMENT gene-or-gene-product	(#PCDATA | frag)*>
<!ATTLIST gene-or-gene-product
		id  ID		#REQUIRED
		equiv		IDREF	#IMPLIED
		appos		(YES|NO)	"NO"
		orig-frag-lex CDATA #IMPLIED
		remapped-to-from	CDATA	#IMPLIED
>

<!-- ============================================================ -->
<!-- ELEMENTS FOR EVENT ANNOTATION                                -->
<!-- ============================================================ -->
<!ELEMENT event (type, (theme | site | locTo | locFrom | product | cause | csite)*, clue?, comment?)>
<!-- ELEMENT event (type, theme*, site*, product*, cause*, csite*, clue, comment?) -->

<!ATTLIST event
		id		ID							#REQUIRED
		assertion		(exist|non-exist)			"exist"
		uncertainty 	(certain|probable|doubtful) "certain"
		copy-of CDATA #IMPLIED
>

<!ELEMENT type EMPTY>
<!ATTLIST type class		CDATA	"UNCLASSIFIED">
<!ATTLIST type subclass		(migration|presence|ToLook)	"migration">
<!ATTLIST type
		idref		IDREF	#IMPLIED
>

<!ELEMENT theme EMPTY>
<!ATTLIST theme
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		manual-multi-idref-processing (True | Done) #IMPLIED
		judged-out	CDATA	#IMPLIED
>

<!ELEMENT site EMPTY>
<!ATTLIST site
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		site_of		CDATA	#IMPLIED
>

<!ELEMENT locTo EMPTY>
<!ATTLIST locTo
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
>
<!ELEMENT locFrom EMPTY>
<!ATTLIST locFrom
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
>
<!ELEMENT csite EMPTY>
<!ATTLIST csite
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
>

<!ELEMENT product EMPTY>
<!ATTLIST product
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
>

<!ELEMENT cause EMPTY>
<!ATTLIST cause
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		manual-multi-idref-processing (True | Done) #IMPLIED
		judged-out	CDATA	#IMPLIED
>

<!ELEMENT clue  (#PCDATA | clueType | linkTheme | linkCause | clueTime | clueLoc | atLoc | fromLoc | toLoc | envLoc | corefTheme | corefSite | corefProduct | corefCause | corefLoc | clueExperiment | clueSpec)*>

<!ELEMENT clueType		(#PCDATA | atLoc)*>
<!ELEMENT linkTheme		(#PCDATA)>
<!ELEMENT linkCause		(#PCDATA)>
<!ELEMENT clueTime		(#PCDATA)>
<!ELEMENT clueLoc		(#PCDATA)>
<!ELEMENT atLoc			(#PCDATA)>
<!ELEMENT fromLoc		(#PCDATA)>
<!ELEMENT toLoc			(#PCDATA)>
<!ATTLIST toLoc
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>
<!ELEMENT envLoc		(#PCDATA)>
<!ELEMENT clueExperiment	(#PCDATA)>
<!ELEMENT clueSpec		(#PCDATA)>

<!ELEMENT corefTheme		(#PCDATA)>
<!ATTLIST corefTheme
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT corefCause		(#PCDATA)>
<!ATTLIST corefCause
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT corefSite		(#PCDATA)>
<!ATTLIST corefSite
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT corefProduct		(#PCDATA)>
<!ATTLIST corefProduct
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT corefLoc		(#PCDATA)>
<!ATTLIST corefLoc
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT comment		(#PCDATA)>

<!-- ============================================================ -->
<!-- ELEMENTS FOR STATIC RELATION ANNOTATION                                -->
<!-- ============================================================ -->
<!ELEMENT staticrel (SRtype?, GGP, BioTerm, tags?, note?)>
<!--ELEMENT staticrel (SRtype, GGP, BioTerm, SRcomment?)-->
<!ATTLIST staticrel
		id		ID	#REQUIRED
		relation	(Yes | No | Unsure) "Yes"
>

<!ELEMENT relation (SRtype, GGP, BioTerm, tags?, note?)>
<!ATTLIST relation
		id		ID	#REQUIRED
		relation	(Yes | No | Unsure) "Yes"
>

<!-- -->
<!ELEMENT SRtype EMPTY>
<!--<!ATTLIST SRtype class		(Equivalent | Specification | Modified_Protein | Isoform | Mutant | Recombinant | Precursor | Experimental_material | Amino_Acid_Motif | Amino_Acid | Peptide| Gene_Component | Protein_Complex | GGP_Group | Chromosomal_Locus | Other)	"Protein_Complex">-->
<!ATTLIST SRtype class		(Equivalent | Specification | Modified_Protein | Isoform | Mutant | Recombinant | Precursor | Experimental_material | Amino_Acid_Motif | Amino_Acid | Peptide| Gene_Component | Protein_Complex | GGP_Group | Chromosomal_Locus | Participate | Other)	"Participate">

<!ELEMENT GGP EMPTY>
<!ATTLIST GGP
		idref		IDREF	#REQUIRED
>

<!ELEMENT BioTerm EMPTY>
<!ATTLIST BioTerm
		idref		IDREF	#REQUIRED
>

<!ELEMENT tags		(#PCDATA)>

<!ELEMENT note		(#PCDATA)>

=== Beira-BF/t4ss-event/original-data/T4SS-virulence-relation/file_20.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION EVENT 2.0//EN" "../GENIAtypes/GENIA_event_20.dtd">
<Annotation created="26/03/2010" creator="Tomoko Ohta" annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=000000000">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>000000000</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">Phylogenetic Diversity of the Rickettsiae</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2">Small subunit rRNA sequences have been determined for representative strains of six species of the family Rickettsiaceae : Rickettsia rickettsii , Rickettsia prowazekii , Rickettsia typhi , Coxiella burnetii , Ehrlichia risticii , and Wolbachia persica .</sentence>
<sentence id="S3">The relationships among these sequences and those of other eubacteria show that all members of the family Rickettsiaceae belong to the so-called purple bacterial phylum .</sentence>
<sentence id="S4">The three representatives of the genus Rickettsia form a tight monophyletic cluster within the alpha subdivision of the purple bacteria .</sentence>
<sentence id="S5">E. risticii also belongs to the alpha subdivision and shows a distant yet specific relationship to the genus Rickettsia .</sentence>
<sentence id="S6">However , the family as a whole is not monophyletic , in that C. burnetii and W. persica are members of the gamma subdivision .</sentence>
<sentence id="S7">The former appears to show a specific , but rather distant , relationship to the genus Legionella .</sentence>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>

=== Beira-BF/t4ss-event/original-data/T4SS-virulence-relation/file_11.xml
<?xml version='1.0'?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION EVENT 2.0//EN" "../GENIAtypes/GENIA_event_20.dtd">
<Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=000000000" created="26/03/2010" creator="Tomoko Ohta"><PubmedArticleSet><PubmedArticle><MedlineCitation>
<PMID>000000000</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">Characterization of the virB Operon from an Agrobucterium tumefaciens <term id="T4" sem="Cell_component">Ti Plasmid</term></sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2">The <term id="T8" sem="Biological_process">virulence</term> genes of the <term id="T9" sem="Bacterium">Agrobacterium tumefaciens</term> <term id="T5" sem="Cell_component">Ti plasmid</term> are grouped into six transcription units and direct the <term id="T1" sem="Biological_process">transfer of T-DNA</term> into plant cells .</sentence>
<sentence id="S3">We report here the nucleotide sequence of the largest vir operon , virB , from the <term id="T6" sem="Cell_component">Ti plasmid pTiA6NC</term> .</sentence>
<sentence id="S4">This operon contains 11 open reading frames , 7 of which show evidence of translational coupling. <gene-or-gene-product id="G1">trpE</gene-or-gene-product> :: virB gene fusions were used to confirm the reading frames of genes <gene-or-gene-product id="G2">virB2</gene-or-gene-product> , <gene-or-gene-product id="G3">4</gene-or-gene-product> , <gene-or-gene-product id="G4">5</gene-or-gene-product> , <gene-or-gene-product id="G5">6</gene-or-gene-product> , <gene-or-gene-product id="G6">7</gene-or-gene-product> , <gene-or-gene-product id="G7">8</gene-or-gene-product> , <gene-or-gene-product id="G8">10</gene-or-gene-product> , and <gene-or-gene-product id="G9">11</gene-or-gene-product> .</sentence>
<sentence id="S5">In addition , the native gene products of <gene-or-gene-product id="G10">virB6</gene-or-gene-product> and <gene-or-gene-product id="G11">virB9</gene-or-gene-product> were identified using maxicell and in vitro transcription-translation techniques , and the <gene-or-gene-product id="G12">VirB9</gene-or-gene-product> protein was found to be proteolytically processed .</sentence>
<sentence id="S6">The codon usage of the predicted virB genes is very similar to the other pTiA6 vir genes and is much less biased than Escherichia coli .</sentence>
<sentence id="S7">Since many of the virB gene products have <term id="T2" sem="Biological_process">secretion</term> signals common to <term id="T3" sem="Biological_process">exported</term> bacterial proteins , it is likely that they will be membrane-associated .</sentence>
<sentence id="S8">We propose that the VirB proteins are involved in the formation of a transmembrane structure which mediates the passage of the transferred T-DNA molecule through the bacterial and plant <term id="T7" sem="Cell_component">cell membranes</term> .</sentence>
</AbstractText>
</Abstract></Article></MedlineCitation></PubmedArticle></PubmedArticleSet></Annotation>

=== Beira-BF/t4ss-event/original-data/GGP-XML_event-and-relation/file_23.xml
<?xml version='1.0'?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION EVENT 2.0//EN" "../GENIAtypes/GENIA_event_20.dtd">
<Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=000000000" created="26/03/2010" creator="Tomoko Ohta"><PubmedArticleSet><PubmedArticle><MedlineCitation>
<PMID>000000000</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">Protein Interactions Involved in <term id="T1" sem="Biological_process"><term id="N3" sem="Cell_component">Nuclear</term> Import</term> of the Agrobacterium <gene-or-gene-product id="G1">VirE2</gene-or-gene-product> Protein in Vivo and in Vitro</sentence>
<event id="E2"><type class="Localization" idref="T1"/><theme idref="G1"/></event></ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2">Agrobacterium , the only known organism capable of trans-kingdom <term id="T2" sem="Biological_process">DNA transfer</term> , genetically transforms plants by transferring a segment of its DNA , T-DNA , into the <term id="T6" sem="Cell_component">nucleus</term> of the host cell where it integrates into the plant genome .</sentence>
<sentence id="S3">One of the central events in this genetic transformation process is <term id="T3" sem="Biological_process"><term id="N2" sem="Cell_component">nuclear</term> import</term> of the <term id="N1" sem="DNA_molecule">T-DNA molecule</term> , which to a large degree is mediated by the bacterial <term id="T4" sem="Biological_process">virulence</term> protein <gene-or-gene-product id="G3">VirE2</gene-or-gene-product> .</sentence>
<relation id="R1">
<SRtype/>
<GGP idref="G3"/>
<BioTerm idref="T4"/></relation>
<event id="E1"><type class="Localization" idref="T3"/><theme idref="N1"/><locTo idref="N2"/></event>
<sentence id="S4"><gene-or-gene-product id="G4">VirE2</gene-or-gene-product> is distinguished by its nuclear targeting , which occurs only in plant but not in animal cells and is facilitated by the cellular <gene-or-gene-product id="G5">VIP1</gene-or-gene-product> protein .</sentence>
<sentence id="S5">The molecular mechanism of the <gene-or-gene-product id="G6">VIP1</gene-or-gene-product> function is still unclear .</sentence>
<sentence id="S6">Here , we used in vitro assays for <term id="T5" sem="Biological_process">nuclear import</term> and quantification of proteinprotein interactions to directly demonstrate formation of ternary complexes between <gene-or-gene-product id="G7">VirE2</gene-or-gene-product> , <gene-or-gene-product id="G8">VIP1</gene-or-gene-product> , and a component of the cellular <term id="T7" sem="Cell_component">nuclear import machinery</term> , <gene-or-gene-product id="G9">karyopherin</gene-or-gene-product> .</sentence>
<event id="E3"><type class="Binding"/><theme idref="G7"/><theme idref="G8"/><theme idref="G9"/><clue>Here , we used in vitro assays for nuclear import and quantification of proteinprotein interactions to directly demonstrate formation of <clueType>ternary complexes</clueType> <linkTheme>between</linkTheme> VirE2 , VIP1 , and a component of the cellular nuclear import machinery , karyopherin .</clue></event>
<sentence id="S7">Our results indicate that <gene-or-gene-product id="G10">VIP1</gene-or-gene-product> functions as a molecular bridge between <gene-or-gene-product id="G11">VirE2</gene-or-gene-product> and <gene-or-gene-product id="G12">karyopherin</gene-or-gene-product> , allowing <gene-or-gene-product id="G13">VirE2</gene-or-gene-product> to utilize the host cell <term id="T8" sem="Cell_component">nuclear import machinery</term> even without being directly recognized by its components .</sentence>
<sentence id="S8"/></AbstractText>
</Abstract></Article></MedlineCitation></PubmedArticle></PubmedArticleSet></Annotation>

=== Beira-BF/t4ss-event/original-data/T4SS-virulence-relation/file_19.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION EVENT 2.0//EN" "../GENIAtypes/GENIA_event_20.dtd">
<Annotation created="26/03/2010" creator="Tomoko Ohta" annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=000000000">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>000000000</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">Partners-in-infection : host proteins involved in the transformation of plant cells by Agrobacterium</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2">Genetic modification of plant cells by Agrobacterium is the only known natural example of <term id="T1" sem="Biological_process">DNA transport</term> between kingdoms .</sentence>
<sentence id="S3">While the bacterial factors involved in Agrobacterium infection have been relatively well characterized , studies of their host cellular partners are just beginning .</sentence>
<sentence id="S4">Here , we describe the plant cell factors that might participate in Agrobacterium-mediated genetic transformation and discuss their possible roles in this process .</sentence>
<sentence id="S5">Because Agrobacterium probably adapts existing cellular processes for its life cycle , identifying the host factors participating in Agrobacterium infection might contribute to a better understanding of such basic biological processes as cell communication , <term id="T2" sem="Biological_process">intracellular transport</term> and DNA repair and recombination as well as help expand the host range of Agrobacterium as a genetic engineering tool .</sentence>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>

=== Beira-BF/t4ss-event/original-data/GGP-XML_event-and-relation/file_21.xml
<?xml version='1.0'?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION EVENT 2.0//EN" "../GENIAtypes/GENIA_event_20.dtd">
<Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=000000000" created="26/03/2010" creator="Tomoko Ohta"><PubmedArticleSet><PubmedArticle><MedlineCitation>
<PMID>000000000</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">The Product of the <gene-or-gene-product id="G1">virB4</gene-or-gene-product> Gene of <term id="N4" sem="Bacterium">Agrobacterium tumefaciens</term> Promotes Accumulation of <gene-or-gene-product id="G2">VirB3</gene-or-gene-product> Protein</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2">The process of <term id="T1" sem="Biological_process"><term id="T7" sem="Cell_component">T-DNA</term> transfer</term> from <term id="N1" sem="Bacterium">Agrobacterium tumefaciens</term> to <term id="N2" sem="Cell_natural">plant cells</term> is thought to involve passage of a DNA-protein complex through a specialized structure in the <term id="T8" sem="Cell_component">bacterial membrane</term> .</sentence>
<event id="E1"><type class="Localization" idref="T1"/><theme idref="T7"/><locFrom idref="N1"/><locTo idref="N2"/></event>
<sentence id="S3">The virB operon of <term id="N5" sem="Bacterium">A. tumefaciens</term> encodes 11 proteins , of which 9 are known to be located in the <term id="T9" sem="Cell_component">membranes</term> and 10 have been shown to be essential for <term id="T2" sem="Biological_process">virulence</term> .</sentence>
<sentence id="S4">Sequence comparisons between proteins encoded by the virB operon and those encoded by operons from <term id="T10" sem="Cell_component">conjugative plasmids</term> indicated that VirB proteins may form a structure similar to a <term id="T11" sem="Cell_component">conjugative pilus</term> .</sentence>
<sentence id="S5">Here , we examine the effects of mutations in <gene-or-gene-product id="G7">virB4</gene-or-gene-product> on the accumulation and <term id="T3" sem="Biological_process">localization</term> of other <term id="N3" sem="Protein_family_or_group">VirB proteins</term> .</sentence>
<event id="E2"><type class="Localization" idref="T3"/><theme idref="N3"/></event>
<sentence id="S6"><gene-or-gene-product id="G9">VirB4</gene-or-gene-product> shares amino acid sequence similarity with the <gene-or-gene-product id="G10">TraC</gene-or-gene-product> protein of plasmid F , which is essential for <term id="T4" sem="Biological_process"><term id="T12" sem="Cell_component">pilus</term> formation</term> in Escherichia coli , and with the <gene-or-gene-product id="G12">PtlC</gene-or-gene-product> protein of Bordetella pertussis , which is required for <term id="T5" sem="Biological_process">toxin secretion</term> .</sentence>
<sentence id="S7">Polar and nonpolar <gene-or-gene-product id="G13">virB4</gene-or-gene-product> mutants were examined , and all were shown to be unable to accumulate <gene-or-gene-product id="G14">VirB3</gene-or-gene-product> protein to wild-type levels .</sentence>
<sentence id="S8">A low level of <gene-or-gene-product id="G15">VirB3</gene-or-gene-product> protein which was present in induced NT1RE cells harboring <gene-or-gene-product id="G16">virB4</gene-or-gene-product> nonpolar mutant pBM1130 was found to associate with the <term id="T13" sem="Cell_component">inner membrane</term> fraction only , whereas in wild-type cells <gene-or-gene-product id="G17">VirB3</gene-or-gene-product> associated with both inner and <term id="T14" sem="Cell_component">outer membranes</term> .</sentence>
<sentence id="S9">The results indicate that for <gene-or-gene-product id="G18">VirB3</gene-or-gene-product> to accumulate in the <term id="T15" sem="Cell_component">outer membrane</term> , <gene-or-gene-product id="G19">VirB4</gene-or-gene-product> must also be present , and it is possible that one role of <gene-or-gene-product id="G20">VirB4</gene-or-gene-product> is in the correct <term id="T6" sem="Biological_process">assembly</term> of a VirB protein membrane structure .</sentence>
</AbstractText>
</Abstract></Article></MedlineCitation></PubmedArticle></PubmedArticleSet></Annotation>

=== Beira-BF/t4ss-event/original-data/T4SS-virulence-relation/file_6.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION EVENT 2.0//EN" "../GENIAtypes/GENIA_event_20.dtd">
<Annotation created="26/03/2010" creator="Tomoko Ohta" annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=000000000">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>000000000</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">Agropine in &quot; null-type &quot; crown gall tumors : Evidence for generality of the opine concept</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2"><term id="T1" sem="Bacterium">Agrobacterium</term> <term id="T3" sem="Cell_component">Ti ( tumor-inducing ) plasmids</term> , the causative agents of crown gall disease , fall into four genetic goups based on the patterns of octopine and nopaline synthesis ( by crown gall tumors ) and catabolism ( by <term id="T2" sem="Bacterium">Agrobacterium tumefaciens</term> ) for which they are responsible .</sentence>
<sentence id="S3">Two classes of <term id="T4" sem="Cell_component">Ti plasmids</term> induce tumors that synthesize neither octopine nor nopaline .</sentence>
<sentence id="S4">The existence of these <term id="T5" sem="Cell_component">Ti plasmids</term> challenged the view that opines such as octopine and nopaline play a central role in crown gall biology .</sentence>
<sentence id="S5">We now report the occurrence of an opine in tumors induced by one of these classes of <term id="T6" sem="Cell_component">Ti plasmids</term> , the &quot; null-type &quot; plasmids typified by pTi Bo542 .</sentence>
<sentence id="S6">The opine was purified by biological enrichment based on its utilization by bacteria containing pTi Bo542 but not by bacteria lacking a <term id="T7" sem="Cell_component">Ti plasmid</term> .</sentence>
<sentence id="S7">The mass spectrum and biological properties of this opine are identical to those of agropine , an opine recently discovered in octopine-type tumors .</sentence>
<sentence id="S8">We propose that null-type <term id="T8" sem="Cell_component">Ti plasmids</term> now be named for their signal opine , agropine-type <term id="T9" sem="Cell_component">Ti plasmids</term> .</sentence>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>

=== Beira-BF/t4ss-event/original-data/T4SS-virulence-relation/file_24.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION EVENT 2.0//EN" "../GENIAtypes/GENIA_event_20.dtd">
<Annotation created="26/03/2010" creator="Tomoko Ohta" annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=000000000">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>000000000</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">Relationships between a new <term id="T3" sem="Cell_component">type IV secretion system</term> and the <term id="T4" sem="Cell_component">icm/dot virulence system</term> of Legionella pneumophila</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2">We describe here a Legionella pneumophila <term id="T5" sem="Cell_component">type IV secretion system</term> that is distinct from the previously described <term id="T6" sem="Cell_component">icm/dot system</term> .</sentence>
<sentence id="S3">This <term id="T7" sem="Cell_component">type IV secretion system</term> contains 11 genes ( lvh ) homologous to genes of other <term id="T8" sem="Cell_component">type IV secretion systems</term> , arranged in a similar manner .</sentence>
<sentence id="S4">The lvh genes were found to be located on a DNA island with a GC content higher than the L. pneumophila <term id="T9" sem="Cell_component">chromosome</term> .</sentence>
<sentence id="S5">In contrast to the <term id="T10" sem="Cell_component">icm/dot system</term> that was shown to be required for intracellular growth in HL-60-derived human macrophages and Acanthamoeba castellanii , the <term id="T11" sem="Cell_component">lvh system</term> was found to be dispensable for intracellular growth in these two hosts .</sentence>
<sentence id="S6">The <term id="T12" sem="Cell_component">lvh system</term> was found to be partially required for RSF1010 <term id="T1" sem="Biological_process">conjugation</term> , a process that was previously shown to be completely dependent on several icm/dot genes .</sentence>
<sentence id="S7">However , results obtained from analysis of double mutants in the icm/dot genes and the lvh genes revealed that lvh genes can substitute for some components of the <term id="T13" sem="Cell_component">icm/dot system</term> for RSF1010 <term id="T2" sem="Biological_process">conjugation</term> , but not for intracellular growth .</sentence>
<sentence id="S8">These results indicate that components of the <term id="T14" sem="Cell_component">icm/dot system</term> and components of the <term id="T15" sem="Cell_component">lvh type IV secretion system</term> are able to interact with one another .</sentence>
<sentence id="S9"></sentence>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>
