=== Beira-BF/t4ss-event/original-data/GENIAtypes/GENIA_event_20.dtd
<!-- ============================================================ -->
<!-- DTD for Genia corpus with term&event annotation              -->
<!-- written by Jin-Dong KIM <jdkim@tsujii.is.s.u-tokyo.ac.jp>    -->
<!-- Date of last modification: November 11 2005                  -->
<!-- ============================================================ -->

<!-- ============================================================ -->
<!-- Labels for term&event annotation                             -->
<!-- ============================================================ -->
<!ENTITY % term.class "(
Element | Inorganic_compound | Organic_compound_other |
Amino_acid_monomer | Peptide | Carbohydrate | Lipid | protein |
Protein_complex | Protein_domain_or_region | Protein_family_or_group |
Protein_molecule | Protein_substructure | DNA |
DNA_domain_or_region | DNA_family_or_group | DNA_molecule | DNA_substructure | RNA |
RNA_domain_or_region | RNA_family_or_group | RNA_molecule | RNA_substructure |
Nucleotide | Polynucleotide |
Cell_component | Cell_cultured | Cell_natural |
Body_region | Tissue_cultured | Tissue_natural |
Multicellular_organism_natural | Multicellular_organism_genetically_modified |
Unicellular_organism | Virus | Bacterium |
Other | Biological_process | Diagnosis | Disease |
Experimental_method | Molecular_function | Therapeutics
)">

<!ENTITY % word.class "(
C | CC | CD | COLON | COMMA | DT | EX | FJJ | FW | IN | JJ | JJR | JJS |
LQT | LRB | LS | MD | NN | NNP | NNPS | NNS | PDT | PERIOD | POS |
PRP | PRPP | RB | RBR | RBS | RP | RQT | RRB | SYM | TO |
VB | VBD | VBG | VBN | VBP | VBZ | WDT | WP | WPP | WRB | FRAG
)">

<!-- ============================================================ -->
<!-- HIERARCHICAL ELEMENTS                                        -->
<!-- ============================================================ -->
<!ELEMENT Annotation (PubmedArticleSet)>
<!ATTLIST Annotation
		annotates CDATA #REQUIRED
		creator   CDATA #IMPLIED
		created   CDATA #IMPLIED
>

<!ELEMENT PubmedArticleSet (PubmedArticle)>
<!ELEMENT PubmedArticle (MedlineCitation)>
<!ELEMENT MedlineCitation (PMID, Article)>
<!ELEMENT Article (ArticleTitle, Abstract)>
<!ELEMENT Abstract (AbstractText)>

<!-- ============================================================ -->
<!-- BLOCK ELEMENTS                                               -->
<!-- ============================================================ -->
<!ELEMENT ArticleTitle (sentence | event | staticrel | relation)+>
<!ELEMENT AbstractText (sentence | event | staticrel | relation)+>
<!ELEMENT PMID (#PCDATA)>

<!-- ============================================================ -->
<!-- LINGUISTIC ELEMENTS                                          -->
<!-- ============================================================ -->
<!ELEMENT sentence	(#PCDATA | cons | term | frag | gene-or-gene-product)*>
<!ATTLIST sentence	id ID	#REQUIRED>

<!ELEMENT cons		(#PCDATA | cons | term | frag | gene-or-gene-product)*>
<!ATTLIST cons 
		sem CDATA #REQUIRED
		lex CDATA #REQUIRED
		id  ID    #REQUIRED
>

<!ELEMENT term		(#PCDATA | term | frag | gene-or-gene-product)*>
<!ATTLIST term
		sem %term.class;	#IMPLIED
		lex CDATA	#IMPLIED
		id  ID		#REQUIRED
		manual-T2G-term-processing (True | False) #IMPLIED
		manual-A-term-processing (True | False) #IMPLIED
		T2G-Is-restructure (True | manual | done) #IMPLIED
		frags CDATA #IMPLIED
		full-lex CDATA #IMPLIED
		old-frag-id CDATA #IMPLIED
		orig-frag-lex CDATA #IMPLIED
		remap-to	CDATA #IMPLIED
		site	CDATA #IMPLIED
		appos		(YES|NO)	"NO"
		idref	CDATA	#IMPLIED
>

<!ELEMENT frag		(#PCDATA | term | gene-or-gene-product)*>
<!ATTLIST frag
		id  ID		#REQUIRED
		idref IDREF	#IMPLIED
		remap-to CDATA	#IMPLIED
		site	CDATA #IMPLIED
>

<!ELEMENT gene-or-gene-product	(#PCDATA | frag)*>
<!ATTLIST gene-or-gene-product
		id  ID		#REQUIRED
		equiv		IDREF	#IMPLIED
		appos		(YES|NO)	"NO"
		orig-frag-lex CDATA #IMPLIED
		remapped-to-from	CDATA	#IMPLIED
>

<!-- ============================================================ -->
<!-- ELEMENTS FOR EVENT ANNOTATION                                -->
<!-- ============================================================ -->
<!ELEMENT event (type, (theme | site | locTo | locFrom | product | cause | csite)*, clue?, comment?)>
<!-- ELEMENT event (type, theme*, site*, product*, cause*, csite*, clue, comment?) -->

<!ATTLIST event
		id		ID							#REQUIRED
		assertion		(exist|non-exist)			"exist"
		uncertainty 	(certain|probable|doubtful) "certain"
		copy-of CDATA #IMPLIED
>

<!ELEMENT type EMPTY>
<!ATTLIST type class		CDATA	"UNCLASSIFIED">
<!ATTLIST type subclass		(migration|presence|ToLook)	"migration">
<!ATTLIST type
		idref		IDREF	#IMPLIED
>

<!ELEMENT theme EMPTY>
<!ATTLIST theme
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		manual-multi-idref-processing (True | Done) #IMPLIED
		judged-out	CDATA	#IMPLIED
>

<!ELEMENT site EMPTY>
<!ATTLIST site
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		site_of		CDATA	#IMPLIED
>

<!ELEMENT locTo EMPTY>
<!ATTLIST locTo
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
>
<!ELEMENT locFrom EMPTY>
<!ATTLIST locFrom
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
>
<!ELEMENT csite EMPTY>
<!ATTLIST csite
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
>

<!ELEMENT product EMPTY>
<!ATTLIST product
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
>

<!ELEMENT cause EMPTY>
<!ATTLIST cause
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		manual-multi-idref-processing (True | Done) #IMPLIED
		judged-out	CDATA	#IMPLIED
>

<!ELEMENT clue  (#PCDATA | clueType | linkTheme | linkCause | clueTime | clueLoc | atLoc | fromLoc | toLoc | envLoc | corefTheme | corefSite | corefProduct | corefCause | corefLoc | clueExperiment | clueSpec)*>

<!ELEMENT clueType		(#PCDATA | atLoc)*>
<!ELEMENT linkTheme		(#PCDATA)>
<!ELEMENT linkCause		(#PCDATA)>
<!ELEMENT clueTime		(#PCDATA)>
<!ELEMENT clueLoc		(#PCDATA)>
<!ELEMENT atLoc			(#PCDATA)>
<!ELEMENT fromLoc		(#PCDATA)>
<!ELEMENT toLoc			(#PCDATA)>
<!ATTLIST toLoc
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>
<!ELEMENT envLoc		(#PCDATA)>
<!ELEMENT clueExperiment	(#PCDATA)>
<!ELEMENT clueSpec		(#PCDATA)>

<!ELEMENT corefTheme		(#PCDATA)>
<!ATTLIST corefTheme
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT corefCause		(#PCDATA)>
<!ATTLIST corefCause
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT corefSite		(#PCDATA)>
<!ATTLIST corefSite
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT corefProduct		(#PCDATA)>
<!ATTLIST corefProduct
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT corefLoc		(#PCDATA)>
<!ATTLIST corefLoc
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT comment		(#PCDATA)>

<!-- ============================================================ -->
<!-- ELEMENTS FOR STATIC RELATION ANNOTATION                                -->
<!-- ============================================================ -->
<!ELEMENT staticrel (SRtype?, GGP, BioTerm, tags?, note?)>
<!--ELEMENT staticrel (SRtype, GGP, BioTerm, SRcomment?)-->
<!ATTLIST staticrel
		id		ID	#REQUIRED
		relation	(Yes | No | Unsure) "Yes"
>

<!ELEMENT relation (SRtype, GGP, BioTerm, tags?, note?)>
<!ATTLIST relation
		id		ID	#REQUIRED
		relation	(Yes | No | Unsure) "Yes"
>

<!-- -->
<!ELEMENT SRtype EMPTY>
<!--<!ATTLIST SRtype class		(Equivalent | Specification | Modified_Protein | Isoform | Mutant | Recombinant | Precursor | Experimental_material | Amino_Acid_Motif | Amino_Acid | Peptide| Gene_Component | Protein_Complex | GGP_Group | Chromosomal_Locus | Other)	"Protein_Complex">-->
<!ATTLIST SRtype class		(Equivalent | Specification | Modified_Protein | Isoform | Mutant | Recombinant | Precursor | Experimental_material | Amino_Acid_Motif | Amino_Acid | Peptide| Gene_Component | Protein_Complex | GGP_Group | Chromosomal_Locus | Participate | Other)	"Participate">

<!ELEMENT GGP EMPTY>
<!ATTLIST GGP
		idref		IDREF	#REQUIRED
>

<!ELEMENT BioTerm EMPTY>
<!ATTLIST BioTerm
		idref		IDREF	#REQUIRED
>

<!ELEMENT tags		(#PCDATA)>

<!ELEMENT note		(#PCDATA)>

=== Beira-BF/t4ss-event/original-data/T4SS-virulence-relation/file_7.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION EVENT 2.0//EN" "../GENIAtypes/GENIA_event_20.dtd">
<Annotation created="26/03/2010" creator="Tomoko Ohta" annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=000000000">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>000000000</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">Altered states : Involvement of phosphorylated <gene-or-gene-product id="G1">CagA</gene-or-gene-product> in the induction of host cellular growth changes by <term id="T1" sem="Bacterium">Helicobacter pylori</term></sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2"><term id="T2" sem="Bacterium">Helicobacter pylori</term> , present in half of the world&apos;s population , is a very successful pathogen .</sentence>
<sentence id="S3">It can survive for decades in the human stomach with few obvious consequences to the host .</sentence>
<sentence id="S4">However , it is also the cause of gastric diseases ranging from gastritis to ulcers to gastric cancer and has been classified a type 1 carcinogen by the World Health Organization .</sentence>
<sentence id="S5">We have previously shown that phosphorylation of a 145-kDa protein and activation of signal transduction pathways are associated with the attachment of <term id="T3" sem="Bacterium">H. pylori</term> to gastric cells .</sentence>
<sentence id="S6">Here we identify the 145-kDa protein as the <term id="T4" sem="Bacterium">H. pylori</term> <gene-or-gene-product id="G2">CagA</gene-or-gene-product> protein .</sentence>
<sentence id="S7">We also show that <gene-or-gene-product id="G3">CagA</gene-or-gene-product> is necessary to induce a growth-factor-like phenotype ( hummingbird ) in host gastric cells similar to that induced by <gene-or-gene-product id="G4">hepatocyte growth factor</gene-or-gene-product> ( <gene-or-gene-product id="G5">HGF</gene-or-gene-product> ) .</sentence>
<sentence id="S8">Additionally , we identify a second cellular phenotype induced after attachment by <term id="T5" sem="Bacterium">H. pylori</term> , which we call SFA ( stress fiber associated ) .</sentence>
<sentence id="S9">SFA is <gene-or-gene-product id="G6">CagA</gene-or-gene-product> independent and is produced by type I and type II <term id="T6" sem="Bacterium">H. pylori</term> .</sentence>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>

=== Beira-BF/t4ss-event/original-data/GGP-XML_event-and-relation/file_15.xml
<?xml version='1.0'?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION EVENT 2.0//EN" "../GENIAtypes/GENIA_event_20.dtd">
<Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=000000000" created="26/03/2010" creator="Tomoko Ohta"><PubmedArticleSet><PubmedArticle><MedlineCitation>
<PMID>000000000</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">Interactions between <gene-or-gene-product id="G1">VirB9</gene-or-gene-product> and <gene-or-gene-product id="G2">VirB10</gene-or-gene-product> Membrane Proteins Involved in Movement of DNA from Agrobacterium tumefaciens into Plant Cells</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2">The 11 VirB proteins from Agrobacterium tumefaciens are predicted to form a membrane-bound complex that mediates the movement of DNA from the bacterium into plant cells .</sentence>
<sentence id="S3">The studies reported here on the possible VirB protein interactions in such a complex demonstrate that <gene-or-gene-product id="G5">VirB9</gene-or-gene-product> and <gene-or-gene-product id="G6">VirB10</gene-or-gene-product> can each form high-molecularweight complexes after treatment with a chemical cross-linker .</sentence>
<sentence id="S4">Analysis of nonpolar virB mutants showed that the formation of the <term id="T2" sem="Cell_component"><gene-or-gene-product id="G8">VirB10</gene-or-gene-product> complexes</term> does not occur in a <gene-or-gene-product id="G9">virB9</gene-or-gene-product> mutant and that <gene-or-gene-product id="G10">VirB9</gene-or-gene-product> and <gene-or-gene-product id="G11">VirB10</gene-or-gene-product> are not components of the same <term id="T3" sem="Cell_component">cross-linked complex</term> .</sentence>
<sentence id="S5"><gene-or-gene-product id="G12">VirB9</gene-or-gene-product> , when stabilized by the concurrent expression of <gene-or-gene-product id="G13">VirB7</gene-or-gene-product> , was shown to be sufficient to permit <gene-or-gene-product id="G14">VirB10</gene-or-gene-product> to cross-link into its usual high-molecular-weight forms in the absence of other Vir proteins .</sentence>
<sentence id="S6">Randomly introduced single point mutations in <gene-or-gene-product id="G16">virB9</gene-or-gene-product> resulted in Agrobacterium strains with severely attenuated <term id="T1" sem="Biological_process">virulence</term> .</sentence>
<staticrel id="R1">
<SRtype/>
<GGP idref="G16"/>
<BioTerm idref="T1"/></staticrel>
<sentence id="S7">Although some of the mutants contained wild-type levels of <gene-or-gene-product id="G17">VirB9</gene-or-gene-product> and displayed an unaltered <gene-or-gene-product id="G18">VirB9</gene-or-gene-product> cross-linking pattern , <gene-or-gene-product id="G19">VirB10</gene-or-gene-product> cross-linking was drastically reduced .</sentence>
<sentence id="S8">We conclude that specific amino acid residues in <gene-or-gene-product id="G20">VirB9</gene-or-gene-product> are necessary for interaction with <gene-or-gene-product id="G21">VirB10</gene-or-gene-product> resulting in the capacity of <gene-or-gene-product id="G22">VirB10</gene-or-gene-product> to participate in high-molecular-weight complexes that can be visualized by chemical cross-linking .</sentence>
<sentence id="S9"/></AbstractText>
</Abstract></Article></MedlineCitation></PubmedArticle></PubmedArticleSet></Annotation>

=== Beira-BF/t4ss-event/original-data/GGP-XML_event-and-relation/file_10.xml
<?xml version='1.0'?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION EVENT 2.0//EN" "../GENIAtypes/GENIA_event_20.dtd">
<Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=000000000" created="26/03/2010" creator="Tomoko Ohta"><PubmedArticleSet><PubmedArticle><MedlineCitation>
<PMID>000000000</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">The <term id="T1" sem="Bacterium">Agrobacterium tumefaciens</term> <gene-or-gene-product id="G1">virB4</gene-or-gene-product> Gene Product Is an Essential <term id="T5" sem="Biological_process">Virulence</term> Protein Requiring an Intact <term id="T16" sem="Molecular_function"><term id="N2" sem="Nucleotide">Nucleoside Triphosphate</term>-Binding</term> Domain</sentence>
<event id="E1"><type class="Binding" idref="T16"/><theme idref="G1"/><theme idref="N2"/></event>
<relation id="R1">
<SRtype/>
<GGP idref="G1"/>
<BioTerm idref="T5"/></relation>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2">Products of the -9.5-kb virB operon are proposed to direct the <term id="T6" sem="Biological_process">export</term> of <term id="T13" sem="Cell_component">T-DNA/protein complexes</term> across the <term id="T2" sem="Bacterium">Agrobacterium tumefaciens</term> envelope en route to plant cells .</sentence>
<sentence id="S3">The presence of conserved nucleoside triphosphate <term id="T17" sem="Molecular_function">( NTP ) -binding</term> domains in <gene-or-gene-product id="G3">VirB4</gene-or-gene-product> and <gene-or-gene-product id="G4">VirB11</gene-or-gene-product> suggests that one or both proteins couple energy , via NTP hydrolysis , to <term id="T7" sem="Biological_process">T-complex transport</term> .</sentence>
<sentence id="S4">To assess the importance of <gene-or-gene-product id="G5">VirB4</gene-or-gene-product> for <term id="T8" sem="Biological_process">virulence</term> , a nonpolar <gene-or-gene-product id="G6">virB4</gene-or-gene-product> null mutation was introduced into the <term id="T14" sem="Cell_component">pTiA6NC plasmid</term> of strain A348 .</sentence>
<relation id="R2">
<SRtype/>
<GGP idref="G5"/>
<BioTerm idref="T8"/></relation>
<sentence id="S5">The 2.37-kb <gene-or-gene-product id="G7">virB4</gene-or-gene-product> coding sequence was deleted precisely by oligonucleotide-directed mutagenesis in vitro .</sentence>
<sentence id="S6">The resulting delta<gene-or-gene-product id="G8">virB4</gene-or-gene-product> mutation was exchanged for the wild-type allele by two sequential recombination events with the counterselectable <term id="T3" sem="Bacterium">Bacillus subtilis</term> <gene-or-gene-product id="G10">sacB</gene-or-gene-product> gene .</sentence>
<sentence id="S7">Two derivatives , A348deltaB4.4 and A348deltaB4.5 , sustained a nonpolar deletion of the wild-type <gene-or-gene-product id="G11">virB4</gene-or-gene-product> allele , as judged by Southern blot hybridization and immunoblot analyses with antibodies specific for <gene-or-gene-product id="G12">VirB4</gene-or-gene-product> , <gene-or-gene-product id="G13">VirB5</gene-or-gene-product> , <gene-or-gene-product id="G14">VirB10</gene-or-gene-product> , and <gene-or-gene-product id="G15">VirB1l</gene-or-gene-product> .</sentence>
<sentence id="S8">Transcription of wild-type <gene-or-gene-product id="G16">virB4</gene-or-gene-product> from the lac promoter restored <term id="T9" sem="Biological_process">virulence</term> to the nonpolar null mutants on a variety of dicotyledonous species , establishing <gene-or-gene-product id="G18">virB4</gene-or-gene-product> as an essential <term id="T10" sem="Biological_process">virulence</term> gene .</sentence>
<relation id="R3">
<SRtype/>
<GGP idref="G16"/>
<BioTerm idref="T9"/></relation>
<relation id="R4">
<SRtype/>
<GGP idref="G18"/>
<BioTerm idref="T10"/></relation>
<sentence id="S9">A substitution of glutamine for Lys-439 and a deletion of Gly-438 , Lys-439 , and Thr-440 within the glycine-rich <term id="T18" sem="Molecular_function">NTP-binding</term> domain ( Gly-Pro-Iso-Gly-Arg-Gly-Lys-Thr ) abolished complementation of A348deltaB4.4 or A348deltaB4.5 , demonstrating that an intact <term id="T19" sem="Molecular_function">NTP-binding</term> domain is critical for <gene-or-gene-product id="G21">VirB4</gene-or-gene-product> function .</sentence>
<sentence id="S10">Merodiploids expressing both the mutant and wild-type <gene-or-gene-product id="G22">virB4</gene-or-gene-product> alleles exhibited lower <term id="T11" sem="Biological_process">virulence</term> than A348 , suggesting that <gene-or-gene-product id="G23">VirB4</gene-or-gene-product> , a <term id="T15" sem="Cell_component">cytoplasmic membrane</term> protein , may contribute as a homo- or heteromultimer to <term id="T4" sem="Bacterium">A. tumefaciens</term> <term id="T12" sem="Biological_process">virulence</term> .</sentence>
<sentence id="S11"/></AbstractText>
</Abstract></Article></MedlineCitation></PubmedArticle></PubmedArticleSet></Annotation>

=== Beira-BF/t4ss-event/original-data/T4SS-virulence-relation/file_8.xml
<?xml version='1.0'?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION EVENT 2.0//EN" "../GENIAtypes/GENIA_event_20.dtd">
<Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=000000000" created="26/03/2010" creator="Tomoko Ohta"><PubmedArticleSet><PubmedArticle><MedlineCitation>
<PMID>000000000</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">Bacterial <term id="T14" sem="Biological_process">secrets of secretion</term> : EuroConference on the biology of <term id="T15" sem="Biological_process">type IV secretion</term> processes</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2"><term id="T23" sem="Cell_component">Type IV secretion systems ( TFSS )</term> mediate <term id="T16" sem="Biological_process">secretion</term> or direct <term id="T17" sem="Biological_process">cell-to-cell transfer</term> of virulence factors ( proteins or protein-DNA complexes ) from many Gram-negative animal , human and plant pathogens , such as <term id="T1" sem="Bacterium">Agrobacterium tumefaciens</term> , <term id="T2" sem="Bacterium">Bartonella tribocorum</term> , <term id="T3" sem="Bacterium">Bordetella pertussis</term> , <term id="T4" sem="Bacterium">Brucella suis</term> , <term id="T5" sem="Bacterium">Helicobacter pylori</term> , <term id="T6" sem="Bacterium">Legionella pneumophila</term> and <term id="T7" sem="Bacterium">Rickettsia prowazekii</term> , into eukaryotic cells .</sentence>
<sentence id="S3">Bacterial <term id="T18" sem="Biological_process">conjugation</term> is also classified as a TFSS-like process mediating the spread of broad-host-range plasmids between Gram-negative bacteria such as RP4 and R388 , which carry antibiotic resistance genes .</sentence>
<sentence id="S4">Genetic , biochemical , cell biological and structural biology experiments led to significant progress in the understanding of several aspects of TFSS processes .</sentence>
<sentence id="S5">X-ray crystallography revealed that homologues of the <term id="T8" sem="Bacterium">A. tumefaciens</term> inner membrane-associated proteins <gene-or-gene-product id="G3">VirB11</gene-or-gene-product> and <gene-or-gene-product id="G4">VirD4</gene-or-gene-product> from <term id="T9" sem="Bacterium">H. pylori</term> and R388 , respectively , may form channels for <term id="T19" sem="Biological_process">substrate translocation</term> or <term id="T20" sem="Biological_process">assembly</term> of the <term id="T24" sem="Cell_component">transmembrane TFSS machinery</term> .</sentence>
<sentence id="S6">Biochemical and cell biological experiments revealed interactions between components of the periplasmic core components <gene-or-gene-product id="G5">VirB8</gene-or-gene-product> , <gene-or-gene-product id="G6">VirB9</gene-or-gene-product> and <gene-or-gene-product id="G7">VirB10</gene-or-gene-product> , which may form the <term id="T25" sem="Cell_component">translocation channel</term> .</sentence>
<sentence id="S7">Analysis of <term id="T10" sem="Bacterium">A. tumefaciens</term> <term id="T21" sem="Biological_process">virulence</term> proteins <gene-or-gene-product id="G8">VirE2</gene-or-gene-product> and <gene-or-gene-product id="G9">VirF</gene-or-gene-product> suggested that the <term id="T22" sem="Biological_process">periplasmic translocation</term> route of the <gene-or-gene-product id="G10">pertussis toxin</gene-or-gene-product> from <term id="T11" sem="Bacterium">B. pertussis</term> may be more generally valid than previously anticipated .</sentence>
<relation id="R1">
<SRtype/>
<GGP idref="G8"/>
<BioTerm idref="T21"/></relation>
<relation id="R2">
<SRtype/>
<GGP idref="G9"/>
<BioTerm idref="T21"/></relation>
<sentence id="S8">Secretion and modification of toxins from <term id="T12" sem="Bacterium">H. pylori</term> and <term id="T13" sem="Bacterium">L. pneumophila</term> profoundly affect host cell metabolism , thus entering the discipline of cellular microbiology .</sentence>
<sentence id="S9">Finally , results from genome sequencing projects revealed the presence of up to three <term id="T26" sem="Cell_component">TFSS</term> in a single organism , and the analysis of their interplay and adaptation to different functions will be a future challenge .</sentence>
<sentence id="S10"><term id="T27" sem="Cell_component">TFSS-carrying plasmids</term> were discovered in different ecosystems , suggesting that genetic exchange may speed up their evolution and adaptation to different cell-cell interactions .</sentence>
<sentence id="S11"/></AbstractText>
</Abstract></Article></MedlineCitation></PubmedArticle></PubmedArticleSet></Annotation>

=== Beira-BF/t4ss-event/original-data/T4SS-virulence-relation/file_14.xml
<?xml version='1.0'?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION EVENT 2.0//EN" "../GENIAtypes/GENIA_event_20.dtd">
<Annotation annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=000000000" created="26/03/2010" creator="Tomoko Ohta"><PubmedArticleSet><PubmedArticle><MedlineCitation>
<PMID>000000000</PMID>
<Article>
<ArticleTitle>
<sentence id="S1"><term id="T4" sem="Bacterium">Helicobacter pylori</term> <term id="T1" sem="Biological_process">Virulence</term> and Genetic Geography</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2">Isolated for the first time in 1982 from human gastric biopsy , Helicobacter pylori is responsible for gastritis , peptic ulcer , and gastric cancer .</sentence>
<sentence id="S3">A pathogenicity island acquired by horizontal transfer , coding for a <term id="T3" sem="Cell_component">type IV secretion system</term> , is a major determinant of <term id="T2" sem="Biological_process">virulence</term> .</sentence>
<sentence id="S4">The infection is now treated with antibiotics , and vaccines are in preparation .</sentence>
<sentence id="S5">The geographic distribution suggests coevolution of man and Helicobacter pylori .</sentence>
</AbstractText>
</Abstract></Article></MedlineCitation></PubmedArticle></PubmedArticleSet></Annotation>

=== Beira-BF/t4ss-event/original-data/T4SS-virulence-relation/file_26.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION EVENT 2.0//EN" "../GENIAtypes/GENIA_event_20.dtd">
<Annotation created="26/03/2010" creator="Tomoko Ohta" annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=000000000">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>000000000</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">A Robust Species Tree for the Alphaproteobacteria</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2">The branching order and coherence of the alphaproteobacterial orders have not been well established , and not all studies have agreed that <term id="T2" sem="Cell_component">mitochondria</term> arose from within the Rickettsiales .</sentence>
<sentence id="S3">A species tree for 72 alphaproteobacteria was produced from a concatenation of alignments for 104 well-behaved protein families .</sentence>
<sentence id="S4">Coherence was upheld for four of the five orders with current standing that were represented here by more than one species .</sentence>
<sentence id="S5">However , the family Hyphomonadaceae was split from the other Rhodobacterales , forming an expanded group with Caulobacterales that also included Parvularcula .</sentence>
<sentence id="S6">The three earliest-branching alphaproteobacterial orders were the Rickettsiales , followed by the Rhodospirillales and then the Sphingomonadales .</sentence>
<sentence id="S7">The principal uncertainty is whether the expanded Caulobacterales group is more closely associated with the Rhodobacterales or the Rhizobiales .</sentence>
<sentence id="S8">The mitochondrial branch was placed within the Rickettsiales as a sister to the combined Anaplasmataceae and Rickettsiaceae , all subtended by the Pelagibacter branch .</sentence>
<sentence id="S9">Pelagibacter genes will serve as useful additions to the bacterial outgroup in future evolutionary studies of mitochondrial genes , including those that have <term id="T1" sem="Biological_process">transferred</term> to the <term id="T3" sem="Cell_component">eukaryotic nucleus</term> .</sentence>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>
